{"name": "test_create_order_with_auth", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "self = <test_create_order.TestCreateOrder object at 0x1067292b0>\norder_data = {'ingredients': ['61c0c5a71d1f82001bdaaa6d', '61c0c5a71d1f82001bdaaa70']}\nauth_token = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDdjZWRjOWVkMjgwMDAxYjUyNjdlNCIsImlhdCI6MTczMjc2MDUwOSwiZXhwIjoxNzMyNzYxNzA5fQ.Ci1g2logt0IJF5uu7bkGLBENPaa_quJZHaym4gOn8x0'\n\n    @allure.feature(\"Создание заказа\")\n    @allure.story(\"Создание заказа с авторизацией\")\n    def test_create_order_with_auth(self, order_data, auth_token):\n        headers = {\"Authorization\": f\"Bearer {auth_token}\"}\n        response = requests.post(f\"{BASE_URL}/orders\", json=order_data, headers=headers)\n>       assert response.status_code == 200\nE       assert 403 == 200\nE        +  where 403 = <Response [403]>.status_code\n\ntest_create_order.py:13: AssertionError"}, "start": 1732760509845, "stop": 1732760510244, "uuid": "58da00b4-ea3e-4a01-b579-fb0754eecdfc", "historyId": "464bb3c9d13e4175367160ee9092f7e1", "testCaseId": "464bb3c9d13e4175367160ee9092f7e1", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_with_auth", "labels": [{"name": "story", "value": "Создание заказа с авторизацией"}, {"name": "feature", "value": "Создание заказа"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "admins-MacBook-Pro.local"}, {"name": "thread", "value": "25651-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}