{"name": "test_create_order_without_auth", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'id' in {'number': 2033}", "trace": "self = <test_create_order.TestCreateOrder object at 0x1028f1e80>\norder_data = {'ingredients': ['61c0c5a71d1f82001bdaaa6d', '61c0c5a71d1f82001bdaaa70']}\n\n    @allure.feature(\"Создание заказа\")\n    @allure.story(\"Попытка создать заказ без авторизации\")\n    def test_create_order_without_auth(self, order_data):\n        \"\"\"Создание заказа без авторизации\"\"\"\n        response = requests.post(f\"{BASE_URL}/orders\", json=order_data)\n    \n        # Проверка успешного ответа при отсутствии авторизации\n        assert response.status_code == 200  # Ожидаем успешный статус 200\n        assert \"order\" in response.json()  # Проверяем, что в ответе есть информация о заказе\n>       assert \"id\" in response.json()[\"order\"]  # Проверяем, что в заказе есть id\nE       AssertionError: assert 'id' in {'number': 2033}\n\ntest_create_order.py:29: AssertionError"}, "description": "Создание заказа без авторизации", "start": 1732767748768, "stop": 1732767749060, "uuid": "1be1bf7e-fa67-4940-ab0a-8d67aec1e102", "historyId": "31626b131e085db93d76c3e2763e1288", "testCaseId": "31626b131e085db93d76c3e2763e1288", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_without_auth", "labels": [{"name": "feature", "value": "Создание заказа"}, {"name": "story", "value": "Попытка создать заказ без авторизации"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "admins-MacBook-Pro.local"}, {"name": "thread", "value": "26309-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}