{"name": "test_update_user_with_auth", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "self = <test_update_user.TestUpdateUser object at 0x1042ef020>\nauth_header = {'Authorization': 'Bearer Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDdjZWRjOWVkMjgwMDAxYjUyNjdlNCIsImlhdCI6MTczMjc2OTE2NCwiZXhwIjoxNzMyNzcwMzY0fQ.lRT2sPtCp31O5eEm_sZpQYasuqtqCM2gLb3ex83uy0w'}\n\n    @allure.feature(\"Изменение данных пользователя\")\n    @allure.story(\"Изменение данных с авторизацией\")\n    def test_update_user_with_auth(self, auth_header):\n        user_data = {\"name\": \"Updated User Name\"}\n        response = requests.patch(f\"{BASE_URL}/auth/user\", json=user_data, headers=auth_header)\n>       assert response.status_code == 200\nE       assert 403 == 200\nE        +  where 403 = <Response [403]>.status_code\n\ntest_update_user.py:13: AssertionError"}, "start": 1732769164556, "stop": 1732769164719, "uuid": "64443015-a4f2-497f-aeeb-d16f571fb84b", "historyId": "ab27f8bb394885cc72f7183d7134c8bd", "testCaseId": "ab27f8bb394885cc72f7183d7134c8bd", "fullName": "tests.test_update_user.TestUpdateUser#test_update_user_with_auth", "labels": [{"name": "feature", "value": "Изменение данных пользователя"}, {"name": "story", "value": "Изменение данных с авторизацией"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user"}, {"name": "subSuite", "value": "TestUpdateUser"}, {"name": "host", "value": "admins-MacBook-Pro.local"}, {"name": "thread", "value": "26799-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user"}]}