{"name": "Создание заказа с неверными хешами ингредиентов", "status": "broken", "statusDetails": {"message": "KeyError: 'invalid_ingredients'", "trace": "self = <test_create_order.TestCreateOrder object at 0x104cecad0>\nauth_header = {'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDdjZWRjOWVkMjgwMDAxYjUyNjdlNCIsImlhdCI6MTczMzI0NjMxOCwiZXhwIjoxNzMzMjQ3NTE4fQ.nd1lOVzGioF5N5QurjcQREO08hEboWNKskdv8jOsDD4'}\n\n    @allure.title(\"Создание заказа с неверными хешами ингредиентов\")\n    def test_create_order_with_invalid_ingredients(self, auth_header):\n        response = requests.post(\n            f\"{BASE_URL}{ENDPOINTS['orders']}\",\n            json={\"ingredients\": ORDER_DATA[\"invalid_ingredients\"]},\n            headers=auth_header\n        )\n        assert response.status_code == 400\n>       assert response.json()[\"message\"] == ERROR_MESSAGES[\"invalid_ingredients\"]\nE       KeyError: 'invalid_ingredients'\n\ntest_create_order.py:57: KeyError"}, "start": 1733246318739, "stop": 1733246318921, "uuid": "9fc9b399-9539-4777-93ab-7e016ba76c3c", "historyId": "8da158c03f34cca19354eabf273e4086", "testCaseId": "8da158c03f34cca19354eabf273e4086", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_with_invalid_ingredients", "labels": [{"name": "feature", "value": "Создание заказа"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "admins-MacBook-Pro.local"}, {"name": "thread", "value": "97235-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}