{"name": "test_create_order_with_invalid_ingredient", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == 500\n +  where 400 = <Response [400]>.status_code", "trace": "self = <test_create_order.TestCreateOrder object at 0x1069cd040>\nauth_token = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDdjZWRjOWVkMjgwMDAxYjUyNjdlNCIsImlhdCI6MTczMjc2NTY2NiwiZXhwIjoxNzMyNzY2ODY2fQ.4z6VgMdAPRjxyTxVv56onKfRJEHoDXqYrzOOD2m8_7s'\n\n    @allure.feature(\"Создание заказа\")\n    @allure.story(\"Попытка создать заказ с невалидными ингредиентами\")\n    def test_create_order_with_invalid_ingredient(self, auth_token):\n        order_data = {\"ingredients\": [\"invalid_hash\"]}\n        headers = {\"Authorization\": f\"{auth_token}\"}\n        response = requests.post(f\"{BASE_URL}/orders\", json=order_data, headers=headers)\n>       assert response.status_code == 500\nE       assert 400 == 500\nE        +  where 400 = <Response [400]>.status_code\n\ntest_create_order.py:38: AssertionError"}, "start": 1732765666091, "stop": 1732765666261, "uuid": "09d0834b-7863-4159-9db7-b599e659dec3", "historyId": "9bf7d65d22acbc46bdc4ddb4293ba878", "testCaseId": "9bf7d65d22acbc46bdc4ddb4293ba878", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_with_invalid_ingredient", "labels": [{"name": "feature", "value": "Создание заказа"}, {"name": "story", "value": "Попытка создать заказ с невалидными ингредиентами"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "admins-MacBook-Pro.local"}, {"name": "thread", "value": "25878-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}