{"name": "test_update_user_with_auth", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "self = <test_update_user.TestUpdateUser object at 0x1021d3aa0>, auth_header = {'Authorization': 'Bearer <accessToken>'}\n\n    @allure.feature(\"Изменение данных пользователя\")\n    @allure.story(\"Изменение данных с авторизацией\")\n    def test_update_user_with_auth(self, auth_header):\n        user_data = {\"name\": \"Updated User Name\"}\n        response = requests.patch(f\"{BASE_URL}/auth/user\", json=user_data, headers=auth_header)\n>       assert response.status_code == 200  # Ожидаем успешное обновление\nE       assert 403 == 200\nE        +  where 403 = <Response [403]>.status_code\n\ntests/test_update_user.py:19: AssertionError"}, "start": 1732753750112, "stop": 1732753750272, "uuid": "8f6335a7-452a-4860-8330-207a1e97283d", "historyId": "ab27f8bb394885cc72f7183d7134c8bd", "testCaseId": "ab27f8bb394885cc72f7183d7134c8bd", "fullName": "tests.test_update_user.TestUpdateUser#test_update_user_with_auth", "labels": [{"name": "feature", "value": "Изменение данных пользователя"}, {"name": "story", "value": "Изменение данных с авторизацией"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user"}, {"name": "subSuite", "value": "TestUpdateUser"}, {"name": "host", "value": "admins-MacBook-Pro.local"}, {"name": "thread", "value": "23750-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user"}]}