{"name": "test_get_orders_with_auth", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "self = <test_get_orders.TestGetOrders object at 0x11895e780>\n\n    def test_get_orders_with_auth(self):\n        headers = {\"Authorization\": \"Bearer <accessToken>\"}\n        response = requests.get(f\"{BASE_URL}/orders\", headers=headers)\n>       assert response.status_code == 200  # Ожидаем успешное получение заказов\nE       assert 403 == 200\nE        +  where 403 = <Response [403]>.status_code\n\ntests/test_get_orders.py:10: AssertionError"}, "start": 1732752225596, "stop": 1732752225880, "uuid": "22f4601d-0d92-4786-a428-18828155ad1d", "historyId": "2fab9c5df7879b7e1f6bf1dc568f2457", "testCaseId": "2fab9c5df7879b7e1f6bf1dc568f2457", "fullName": "tests.test_get_orders.TestGetOrders#test_get_orders_with_auth", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestGetOrders"}, {"name": "host", "value": "admins-MacBook-Pro.local"}, {"name": "thread", "value": "23420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}